title: Baking a Cake
description: How to bake a cake in 4 easy steps
template:
  repo: baking-a-cake-template
  name: baking-a-cake
  description: Cake-Bake
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
